// Deploy MockUSDC + HyperSettleSpoke to Base Sepolia using the operator key
// generated by init-keys.ts. Mints test mUSDC to the operator (for the user-A
// deposit) and to the spoke contract (for vault liquidity).
//
// Writes addresses to .netting-testnet/evm.json.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  createPublicClient,
  createWalletClient,
  formatEther,
  http,
  keccak256,
  stringToBytes,
  type Address,
  type Hex,
} from "viem";
import { privateKeyToAccount, generatePrivateKey } from "viem/accounts";
import { baseSepolia } from "viem/chains";

const REPO_ROOT = join(__dirname, "../../../..");
const STATE_DIR = join(REPO_ROOT, ".netting-testnet");
const EVM_KEY_PATH = join(STATE_DIR, "operator-evm.json");
const EVM_STATE_PATH = join(STATE_DIR, "evm.json");
const FORGE_OUT = join(REPO_ROOT, "packages/evm-spoke/out");

const RPC_URL = process.env.BASE_SEPOLIA_RPC ?? "https://sepolia.base.org";
const BASE_SEPOLIA_WORMHOLE = "0x79A1027a6A159502049F10906D333EC57E95F083" as const;

const SCALE = 1_000_000n;
const HUB_CHAIN_SOLANA = 1;
const SELF_DOMAIN = 7;

function loadArtifact(name: string): { abi: any; bytecode: Hex } {
  const path = join(FORGE_OUT, `${name}.sol`, `${name}.json`);
  const json = JSON.parse(readFileSync(path, "utf8"));
  const bytecode = json.bytecode?.object as Hex;
  if (!bytecode || !bytecode.startsWith("0x")) {
    throw new Error(`forge artifact missing bytecode: ${name}`);
  }
  return { abi: json.abi, bytecode };
}

async function main() {
  mkdirSync(STATE_DIR, { recursive: true });
  const operatorJson = JSON.parse(readFileSync(EVM_KEY_PATH, "utf8")) as {
    privateKey: `0x${string}`;
    address: Address;
  };
  const operator = privateKeyToAccount(operatorJson.privateKey);

  const publicClient = createPublicClient({
    chain: baseSepolia,
    transport: http(RPC_URL),
  });
  const wallet = createWalletClient({
    account: operator,
    chain: baseSepolia,
    transport: http(RPC_URL),
  });

  const bal = await publicClient.getBalance({ address: operator.address });
  console.log(`Operator      : ${operator.address}`);
  console.log(`Balance       : ${formatEther(bal)} ETH`);
  console.log(`RPC           : ${RPC_URL}`);
  if (bal === 0n) {
    throw new Error("Operator has 0 ETH on Base Sepolia. Fund it first.");
  }

  // Fresh Ika ECDSA dWallet key controlled by us — registered on the spoke
  // as the signer authorized to release settlements.
  const ikaKey = generatePrivateKey();
  const ikaAddress = privateKeyToAccount(ikaKey).address;

  const usdcArtifact = loadArtifact("MockUSDC");
  const spokeArtifact = loadArtifact("HyperSettleSpoke");

  console.log("\nDeploying MockUSDC …");
  const usdcHash = await wallet.deployContract({
    abi: usdcArtifact.abi,
    bytecode: usdcArtifact.bytecode,
    account: operator,
    chain: baseSepolia,
  });
  const usdcReceipt = await publicClient.waitForTransactionReceipt({ hash: usdcHash });
  const usdcAddr = usdcReceipt.contractAddress!;
  console.log(`  ✓ MockUSDC at ${usdcAddr}  (tx ${usdcHash})`);

  console.log("\nDeploying HyperSettleSpoke …");
  const spokeHash = await wallet.deployContract({
    abi: spokeArtifact.abi,
    bytecode: spokeArtifact.bytecode,
    args: [operator.address, HUB_CHAIN_SOLANA, SELF_DOMAIN, BASE_SEPOLIA_WORMHOLE, ikaAddress],
    account: operator,
    chain: baseSepolia,
  });
  const spokeReceipt = await publicClient.waitForTransactionReceipt({ hash: spokeHash });
  const spokeAddr = spokeReceipt.contractAddress!;
  console.log(`  ✓ HyperSettleSpoke at ${spokeAddr}  (tx ${spokeHash})`);

  const ticker = keccak256(stringToBytes("USDC"));
  const assetHash = keccak256(stringToBytes("base:USDC"));

  console.log("\nBinding USDC ticker …");
  const bindHash = await wallet.writeContract({
    address: spokeAddr,
    abi: spokeArtifact.abi,
    functionName: "bindTicker",
    args: [ticker, usdcAddr],
    account: operator,
    chain: baseSepolia,
  });
  await publicClient.waitForTransactionReceipt({ hash: bindHash });
  console.log(`  ✓ bindTicker tx ${bindHash}`);

  console.log("\nMinting mUSDC liquidity …");
  // Operator gets 5 mUSDC to spend as user A (the demo uses 1.01).
  // Spoke vault gets 5 mUSDC as outbound liquidity (the demo pays out 1.00).
  const operatorMint = 5n * SCALE;
  const vaultMint = 5n * SCALE;
  const mintOpHash = await wallet.writeContract({
    address: usdcAddr,
    abi: usdcArtifact.abi,
    functionName: "mint",
    args: [operator.address, operatorMint],
    account: operator,
    chain: baseSepolia,
  });
  await publicClient.waitForTransactionReceipt({ hash: mintOpHash });
  console.log(`  ✓ operator +5.000000 mUSDC  (tx ${mintOpHash})`);

  const mintVaultHash = await wallet.writeContract({
    address: usdcAddr,
    abi: usdcArtifact.abi,
    functionName: "mint",
    args: [spokeAddr, vaultMint],
    account: operator,
    chain: baseSepolia,
  });
  await publicClient.waitForTransactionReceipt({ hash: mintVaultHash });
  console.log(`  ✓ vault    +5.000000 mUSDC  (tx ${mintVaultHash})`);

  const state = {
    network: "base-sepolia",
    chainId: 84532,
    wormholeChainId: 10004,
    selfDomain: SELF_DOMAIN,
    hubChainSolana: HUB_CHAIN_SOLANA,
    rpc: RPC_URL,
    operator: operator.address,
    spokeAddr,
    usdcAddr,
    wormholeAddr: BASE_SEPOLIA_WORMHOLE,
    ikaPrivateKey: ikaKey,
    ikaAddress,
    ticker,
    assetHash,
    deployedAt: new Date().toISOString(),
    deployTxs: {
      usdc: usdcHash,
      spoke: spokeHash,
      bindTicker: bindHash,
      mintOperator: mintOpHash,
      mintVault: mintVaultHash,
    },
  };
  writeFileSync(EVM_STATE_PATH, JSON.stringify(state, null, 2));

  console.log("\n──────────────────────────────────────────────");
  console.log("  EVM testnet deploy complete");
  console.log("──────────────────────────────────────────────");
  console.log(`  Spoke    : https://sepolia.basescan.org/address/${spokeAddr}`);
  console.log(`  MockUSDC : https://sepolia.basescan.org/address/${usdcAddr}`);
  console.log(`  State    : ${EVM_STATE_PATH}`);
}

main().catch((e) => {
  console.error("EVM deploy failed:", e);
  process.exit(1);
});
